server:
  port: 8088

spring:
  # 环境设置：dev、test、prod
  application:
    name: service-edu
  #环境配置
  profiles:
    active: dev

  #返回json的全局时间格式 -- 时区东八区
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #数据源：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://121.40.160.237:3306/guli?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    url: jdbc:mysql://121.40.160.237:3306/guli?serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: 123456

#mybatis-plus配置
mybatis-plus:
  #驼峰式关闭
  configuration:
    map-underscore-to-camel-case: false
    #日志打印-控制台
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志级别
#logging:
#  level:
#    root: debug